name: Maven Release

on: workflow_dispatch

jobs:
  build:
    name: Cut a Maven Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          # Use Java LTS version
          java-version: 11
          server-id: sonatype-nexus-staging
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Prepare Release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: OSSRH_PW_SHH # ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: SUPER_SECRET # ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cat ~/.m2/settings.xml
          mvn -V -B release:prepare -DdryRun=true
      # mvn -V -B release:prepare
      # mvn -V -B release:perform
