name: Maven Site

on: workflow_dispatch

jobs:
  build:
    name: Generate Maven Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          # Use Java LTS version
          java-version: 11
      - name: Build Plugin
        run: mvn -V -B install
      - name: Build Site
        run: mvn -V -B site site:stage
      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Install SSH key for Publish to gh-pages
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      # - name: Configure Github Server for Publishing
      #  uses:
      #    awhitford/maven-settings-action@servers-dist
      #    # s4u/maven-settings-action@v2
      #  with:
      #    githubServer: false
      #    servers: |
      #      [{
      #        "id": "awhitford-github-server",
      #        "username": "git",
      #        "privateKey": "${user.home}/.ssh/id_rsa"
      #      }]
      - name: Publish Site to GitHub Pages
        run: mvn -V -B scm-publish:publish-scm
